language: scala
scala:
  - 2.11.4
jdk:
  - openjdk7
env:
  - ACTIVATOR_VERSION=1.2.12
install:
  - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - npm install
script:
  - activator-${ACTIVATOR_VERSION}-minimal/activator "test-only *Spec"
  - grunt test
notifications:
  recipients:
    - matthieu.nicolas@loria.fr
  email:
    on_success: change
    on_failure: always
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"