plm:
  image: webplm
  volumes:
    - "~/.plm:/.plm"
  ports:
    - "80:9000"
  environment: 
    PLMACCOUNTS_CLIENT_SECRET:
  links:
    - accounts
    - profiles
accounts:
  image: plm-accounts
  ports:
    - "3000:3000"
  links:
    - db
profiles:
  image: plm-profiles
  ports:
    - "3001:3000"
  links:
    - db
db:
  image: mongo
  volumes:
    - "~/mongodb/data:/data/db"
  ports: 
    - "27017:27017"