nginx:
  image: nginx
  ports:
    - "80:80"
messagequeue:
  image: rabbitmq
judge:
  image: plm-judge
  restart: always
  links:
    - messagequeue:messageq
  cpuset: 0-3
plm:
  image: webplm
  volumes:
    - "~/.plm:/root/.plm"
    - "~/webPLM/logs/:/app/webplm-dist/logs"
  ports:
    - "443:9443"
  environment: 
    GITHUB_CLIENT_SECRET:
    GOOGLE_CLIENT_SECRET:
    PLMACCOUNTS_CLIENT_SECRET:
  links:
    - accounts
    - profiles
    - messagequeue:messageq
accounts:
  image: plm-accounts
  ports:
    - "9000:3000"
  links:
    - db
profiles:
  image: plm-profiles
  ports:
    - "8080:3000"
  links:
    - db
db:
  image: mongo
  volumes:
    - "~/mongodb/data:/data/db"
  ports: 
    - "27017:27017"
